require_relative 'PORIS'

class ARCGenIIIPORIS < PORISDoc
	def initialize(project_id)
		super(project_id)
		i1_sysARCGenIII = PORISSys.new('ARCGenIII')
		self.addItem(i1_sysARCGenIII)
		i1_sysARCGenIII.setIdent('ARC-0001')
		i1_sysARCGenIII.setDescription('Modelo PORIS que describe el comportamiento de la API de ARCGenIII adaptada para Osiris.
Nota: En algunos casos hemos restringido los valores que la API acepta en sus parámetros para que el usuario no configure el detector de OSIRIS de forma errónea.')
		i4_mdReal = PORISMode.new('Real')
		self.addItem(i4_mdReal)
		i4_mdReal.setIdent('ARC-0002')
		i4_mdReal.setDescription('Modo normal del controlador ARCGenIII que hace uso del hardware real.  Si la configuración se realiza de este modo, la API es usada, y por tanto es necesario disponer de un equipo con la tarjeta R-66 y el controlador ARCGenIII, ambos de astrocam.com.')
		i5_mdEmulated = PORISMode.new('Emulated')
		self.addItem(i5_mdEmulated)
		i5_mdEmulated.setIdent('ARC-0003')
		i5_mdEmulated.setDescription('Modo emulado del controlador ARCGenIII que no hace uso del hardware real.
Si la configuración se realiza en este modo, las llamadas a la API se evitan, y se selecciona una imagen FITS para entregársela al usuario.  Este modo es útil para desarrollar la integración del DAS de OSIRIS con la DataFactory, o para poder emular el instrumento en el entorno GCS sin necesidad de usar el hardware real.')
		i6_sysFirmware = PORISSys.new('Firmware')
		self.addItem(i6_sysFirmware)
		i6_sysFirmware.setIdent('ARC-0004')
		i6_sysFirmware.setDescription('Componente de firmware, que permite escoger la versión de firmware que se cargará en el controlador.')
		i9_mdosiris3 = PORISMode.new('osiris3')
		self.addItem(i9_mdosiris3)
		i9_mdosiris3.setIdent('ARC-0005')
		i9_mdosiris3.setDescription('Segunda versión del firmware de ARCGenIII que da soporte a los modos especiales desarrollados en LISA para Osiris.
Nota: en la actualidad usa el mismo fichero de firmware que la opción osiris2.')
		i10_mdtim = PORISMode.new('tim')
		self.addItem(i10_mdtim)
		i10_mdtim.setIdent('ARC-0006')
		i10_mdtim.setDescription('Versión oficial de firmware de ARCGenIII, desarrollada por astro-cam.  No incorpora los modos especiales desarrollados en LISA para Osiris.')
		i11_mdosiris2 = PORISMode.new('osiris2')
		self.addItem(i11_mdosiris2)
		i11_mdosiris2.setIdent('ARC-0007')
		i11_mdosiris2.setDescription('Primera versión del firmware de ARCGenIII que da soporte a los modos especiales desarrollados en LISA para Osiris.')
		i12_mdosiris4 = PORISMode.new('osiris4')
		self.addItem(i12_mdosiris4)
		i12_mdosiris4.setIdent('ARC-0008')
		i12_mdosiris4.setDescription('Tercera versión del firmware de ARCGenIII que da soporte a los modos especiales desarrollados en LISA para Osiris.
Nota: en la actualidad usa el mismo fichero de firmware que la opción osiris3.')
		i13_mdosiris5 = PORISMode.new('osiris5')
		self.addItem(i13_mdosiris5)
		i13_mdosiris5.setIdent('ARC-0009')
		i13_mdosiris5.setDescription('Cuarta versión del firmware de ARCGenIII que da soporte a los modos especiales desarrollados en LISA para Osiris.
Nota: en la actualidad usa el mismo fichero de firmware que la opción osiris4.')
		i14_sysVariants = PORISSys.new('Variants')
		self.addItem(i14_sysVariants)
		i14_sysVariants.setIdent('ARC-0010')
		i14_sysVariants.setDescription('Componente que engloba las variantes de parámetros que se incluyen en las diferentes versiones de firmware.')
		i17_mdNormal = PORISMode.new('Normal')
		self.addItem(i17_mdNormal)
		i17_mdNormal.setIdent('ARC-0011')
		i17_mdNormal.setDescription('Modo que selecciona la variante Normal de parámetros, que da servicio al firmware tim.')
		i18_mdExtended = PORISMode.new('Extended')
		self.addItem(i18_mdExtended)
		i18_mdExtended.setIdent('ARC-0012')
		i18_mdExtended.setDescription('Modo que selecciona la variante Extendida de parámetros, que da servicio a los diferentes firmware osirisX.')
		i19_mdExtended_2 = PORISMode.new('Extended_2')
		self.addItem(i19_mdExtended_2)
		i19_mdExtended_2.setIdent('ARC-0013')
		i19_mdExtended_2.setDescription('')
		i20_sysAcquisition = PORISSys.new('Acquisition')
		self.addItem(i20_sysAcquisition)
		i20_sysAcquisition.setIdent('ARC-0014')
		i20_sysAcquisition.setDescription('')
		i23_mdNormal = PORISMode.new('Normal')
		self.addItem(i23_mdNormal)
		i23_mdNormal.setIdent('ARC-0015')
		i23_mdNormal.setDescription('')
		i24_mdNormalWindow = PORISMode.new('NormalWindow')
		self.addItem(i24_mdNormalWindow)
		i24_mdNormalWindow.setIdent('ARC-0016')
		i24_mdNormalWindow.setDescription('')
		i25_mdFrameTransfer = PORISMode.new('FrameTransfer')
		self.addItem(i25_mdFrameTransfer)
		i25_mdFrameTransfer.setIdent('ARC-0017')
		i25_mdFrameTransfer.setDescription('')
		i26_mdShuffling = PORISMode.new('Shuffling')
		self.addItem(i26_mdShuffling)
		i26_mdShuffling.setIdent('ARC-0018')
		i26_mdShuffling.setDescription('')
		i27_mdCalibration = PORISMode.new('Calibration')
		self.addItem(i27_mdCalibration)
		i27_mdCalibration.setIdent('ARC-0019')
		i27_mdCalibration.setDescription('')
		i47_prBinning = PORISParam.new('Binning')
		self.addItem(i47_prBinning)
		i47_prBinning.setIdent('ARC-0031')
		i47_prBinning.setDescription('Componente que configura el binning a ser usado.
Nota: La API de ARCGenIII permite comprimir la imagen tanto en vertical como en horizontal según factores numéricos que pueden ser de entidad considerable.  Hemos restringido el factor de compresión a x1 (sin compresión) o x2 (con compresión factor 2) para que el usuario no pueda programar valores incompatibles con el detector de Osiris.')
		i55_mdOff = PORISMode.new('Off')
		self.addItem(i55_mdOff)
		i55_mdOff.setIdent('ARC-0036')
		i55_mdOff.setDescription('Modo desactivado del binning, que fuerza el valor 1x1, sin compresión en ninguna de las dos coordenadas.')
		i56_mdAll = PORISMode.new('All')
		self.addItem(i56_mdAll)
		i56_mdAll.setIdent('ARC-0037')
		i56_mdAll.setDescription('Modo completo del binning, que permite al usuario escoger cualquiera de los cuatro valores de compresión.')
		i57_mdSquare = PORISMode.new('Square')
		self.addItem(i57_mdSquare)
		i57_mdSquare.setIdent('ARC-0038')
		i57_mdSquare.setDescription('Modo cuadrado del binning, sólo permite valores de binning que sean iguales en la vertical y la horizontal.
* 1x1: ninguna compresión.
* 2x2: compresión en ambas coordenadas.')
		i51_vl1x1 = PORISValue.new('1x1')
		self.addItem(i51_vl1x1)
		i51_vl1x1.setIdent('ARC-0032')
		i51_vl1x1.setDescription('Sin compresión de píxeles, ni en horizontal ni en vertical.')
		i52_vl1x2 = PORISValue.new('1x2')
		self.addItem(i52_vl1x2)
		i52_vl1x2.setIdent('ARC-0033')
		i52_vl1x2.setDescription('Compresión x2 en la coordenadas vertical, sin compresión en la horizontal.')
		i53_vl2x1 = PORISValue.new('2x1')
		self.addItem(i53_vl2x1)
		i53_vl2x1.setIdent('ARC-0034')
		i53_vl2x1.setDescription('Compresión x2 en la coordenada horizontal, sin compresión en la vertical.')
		i54_vl2x2 = PORISValue.new('2x2')
		self.addItem(i54_vl2x2)
		i54_vl2x2.setIdent('ARC-0035')
		i54_vl2x2.setDescription('Compresión x2 tanto en la coordenadas horizontal como en la vertical.')
		i113_prShuffleLines = PORISParam.new('ShuffleLines')
		self.addItem(i113_prShuffleLines)
		i113_prShuffleLines.setIdent('ARC-0094')
		i113_prShuffleLines.setDescription('')
		i118_mdNormal = PORISMode.new('Normal')
		self.addItem(i118_mdNormal)
		i118_mdNormal.setIdent('ARC-0096')
		i118_mdNormal.setDescription('')
		i117_vlFull_Range = PORISValueFloat.new('Full_Range',0.0,200.0,1000.0)
		self.addItem(i117_vlFull_Range)
		i117_vlFull_Range.setIdent('ARC-0095')
		i117_vlFull_Range.setDescription('')
		i119_prShiftNumber = PORISParam.new('ShiftNumber')
		self.addItem(i119_prShiftNumber)
		i119_prShiftNumber.setIdent('ARC-0097')
		i119_prShiftNumber.setDescription('')
		i124_mdNormal = PORISMode.new('Normal')
		self.addItem(i124_mdNormal)
		i124_mdNormal.setIdent('ARC-0099')
		i124_mdNormal.setDescription('')
		i123_vlFull_Range = PORISValueFloat.new('Full_Range',0.0,5.0,1000.0)
		self.addItem(i123_vlFull_Range)
		i123_vlFull_Range.setIdent('ARC-0098')
		i123_vlFull_Range.setDescription('')
		i28_sysDimensions = PORISSys.new('Dimensions')
		self.addItem(i28_sysDimensions)
		i28_sysDimensions.setIdent('ARC-0020')
		i28_sysDimensions.setDescription('Componente que determina las dimensiones de la imagen a obtener, mediante los parámetros de filas (uiRows), columnas (uiColumns) y la configuración del subcomponente Binning.')
		i31_mdNormal = PORISMode.new('Normal')
		self.addItem(i31_mdNormal)
		i31_mdNormal.setIdent('ARC-0021')
		i31_mdNormal.setDescription('Modo normal del componente Dimensions, permite que todos sus parámetros se configuren en sus rangos completos, compatibles con el detector de Osiris.')
		i32_mdFT = PORISMode.new('FT')
		self.addItem(i32_mdFT)
		i32_mdFT.setIdent('ARC-0022')
		i32_mdFT.setDescription('')
		i33_pruiCols = PORISParam.new('uiCols')
		self.addItem(i33_pruiCols)
		i33_pruiCols.setIdent('ARC-0023')
		i33_pruiCols.setDescription('Parámetro que define el número de columnas del detector que se quieren utilizar para obtener la próxima imagen.  Las columnas se cuentan en píxeles físicos, independientemente de la configuración de binning.')
		i38_mdNormal = PORISMode.new('Normal')
		self.addItem(i38_mdNormal)
		i38_mdNormal.setIdent('ARC-0025')
		i38_mdNormal.setDescription('Modo normal de uiCols, que activa el rango normal (completo).')
		i37_vlFull_Range = PORISValueFloat.new('Full_Range',0.0,4096.0,4096.0)
		self.addItem(i37_vlFull_Range)
		i37_vlFull_Range.setIdent('ARC-0024')
		i37_vlFull_Range.setDescription('Rango completo para el parámetro de columnas uiCols.  Se restringe para que no pueda ser superior al detector de OSIRIS.')
		i39_pruiRows = PORISParam.new('uiRows')
		self.addItem(i39_pruiRows)
		i39_pruiRows.setIdent('ARC-0026')
		i39_pruiRows.setDescription('Parámetro que define el número de filas del detector que se quieren utilizar para obtener la próxima imagen.  Las filas se cuentan en píxeles físicos, independientemente de la configuración de binning.')
		i45_mdNormal = PORISMode.new('Normal')
		self.addItem(i45_mdNormal)
		i45_mdNormal.setIdent('ARC-0029')
		i45_mdNormal.setDescription('Modo normal de uiRows, que activa el rango normal (completo).')
		i46_mdHalf = PORISMode.new('Half')
		self.addItem(i46_mdHalf)
		i46_mdHalf.setIdent('ARC-0030')
		i46_mdHalf.setDescription('')
		i43_vlFull_Range = PORISValueFloat.new('Full_Range',0.0,4112.0,4112.0)
		self.addItem(i43_vlFull_Range)
		i43_vlFull_Range.setIdent('ARC-0027')
		i43_vlFull_Range.setDescription('Rango completo para el parámetro de filas uiRows.  Se restringe para que no pueda ser superior al detector de OSIRIS.')
		i44_vlFTRange = PORISValueFloat.new('FTRange',0.0,2056.0,2056.0)
		self.addItem(i44_vlFTRange)
		i44_vlFTRange.setIdent('ARC-0028')
		i44_vlFTRange.setDescription('')
		i58_sysOutputSource = PORISSys.new('OutputSource')
		self.addItem(i58_sysOutputSource)
		i58_sysOutputSource.setIdent('ARC-0039')
		i58_sysOutputSource.setDescription('Componente que permite al usuario escoger la fuente de salida del controlador.
TODO: Preguntar a Enrique para mejorar esta descripción.')
		i61_md0x0 = PORISMode.new('0x0')
		self.addItem(i61_md0x0)
		i61_md0x0.setIdent('ARC-0040')
		i61_md0x0.setDescription('TODO: Hablar con Enrique para escribir esta descripción.')
		i62_md0x1 = PORISMode.new('0x1')
		self.addItem(i62_md0x1)
		i62_md0x1.setIdent('ARC-0041')
		i62_md0x1.setDescription('TODO: Hablar con Enrique para escribir esta descripción.')
		i63_md0x2 = PORISMode.new('0x2')
		self.addItem(i63_md0x2)
		i63_md0x2.setIdent('ARC-0042')
		i63_md0x2.setDescription('TODO: Hablar con Enrique para escribir esta descripción.')
		i64_md0x3 = PORISMode.new('0x3')
		self.addItem(i64_md0x3)
		i64_md0x3.setIdent('ARC-0043')
		i64_md0x3.setDescription('TODO: Hablar con Enrique para escribir esta descripción.')
		i65_mdTWO = PORISMode.new('TWO')
		self.addItem(i65_mdTWO)
		i65_mdTWO.setIdent('ARC-0044')
		i65_mdTWO.setDescription('')
		i66_mdALL = PORISMode.new('ALL')
		self.addItem(i66_mdALL)
		i66_mdALL.setIdent('ARC-0045')
		i66_mdALL.setDescription('')
		i67_sysRecomposition = PORISSys.new('Recomposition')
		self.addItem(i67_sysRecomposition)
		i67_sysRecomposition.setIdent('ARC-0046')
		i67_sysRecomposition.setDescription('')
		i70_mdNone = PORISMode.new('None')
		self.addItem(i70_mdNone)
		i70_mdNone.setIdent('ARC-0047')
		i70_mdNone.setDescription('')
		i71_mdSerial = PORISMode.new('Serial')
		self.addItem(i71_mdSerial)
		i71_mdSerial.setIdent('ARC-0048')
		i71_mdSerial.setDescription('')
		i72_mdQuadCCD = PORISMode.new('QuadCCD')
		self.addItem(i72_mdQuadCCD)
		i72_mdQuadCCD.setIdent('ARC-0049')
		i72_mdQuadCCD.setDescription('')
		i73_mdParallel = PORISMode.new('Parallel')
		self.addItem(i73_mdParallel)
		i73_mdParallel.setIdent('ARC-0050')
		i73_mdParallel.setDescription('')
		i74_mdQuadIR = PORISMode.new('QuadIR')
		self.addItem(i74_mdQuadIR)
		i74_mdQuadIR.setIdent('ARC-0051')
		i74_mdQuadIR.setDescription('')
		i75_mdCDSQuad = PORISMode.new('CDSQuad')
		self.addItem(i75_mdCDSQuad)
		i75_mdCDSQuad.setIdent('ARC-0052')
		i75_mdCDSQuad.setDescription('')
		i76_mdHawaiiRG = PORISMode.new('HawaiiRG')
		self.addItem(i76_mdHawaiiRG)
		i76_mdHawaiiRG.setIdent('ARC-0053')
		i76_mdHawaiiRG.setDescription('')
		i77_sysExposureCtrl = PORISSys.new('ExposureCtrl')
		self.addItem(i77_sysExposureCtrl)
		i77_sysExposureCtrl.setIdent('ARC-0054')
		i77_sysExposureCtrl.setDescription('')
		i80_mdNormal = PORISMode.new('Normal')
		self.addItem(i80_mdNormal)
		i80_mdNormal.setIdent('ARC-0055')
		i80_mdNormal.setDescription('')
		i81_mdCalibration = PORISMode.new('Calibration')
		self.addItem(i81_mdCalibration)
		i81_mdCalibration.setIdent('ARC-0056')
		i81_mdCalibration.setDescription('')
		i82_mdNoShutter = PORISMode.new('NoShutter')
		self.addItem(i82_mdNoShutter)
		i82_mdNoShutter.setIdent('ARC-0057')
		i82_mdNoShutter.setDescription('')
		i83_mdFT = PORISMode.new('FT')
		self.addItem(i83_mdFT)
		i83_mdFT.setIdent('ARC-0058')
		i83_mdFT.setDescription('')
		i84_sysSubarrayFeature = PORISSys.new('SubarrayFeature')
		self.addItem(i84_sysSubarrayFeature)
		i84_sysSubarrayFeature.setIdent('ARC-0079')
		i84_sysSubarrayFeature.setDescription('')
		i87_mdOff = PORISMode.new('Off')
		self.addItem(i87_mdOff)
		i87_mdOff.setIdent('ARC-0080')
		i87_mdOff.setDescription('')
		i88_mdOn = PORISMode.new('On')
		self.addItem(i88_mdOn)
		i88_mdOn.setIdent('ARC-0081')
		i88_mdOn.setDescription('')
		i89_prRows = PORISParam.new('Rows')
		self.addItem(i89_prRows)
		i89_prRows.setIdent('ARC-0082')
		i89_prRows.setDescription('')
		i94_mdNormal = PORISMode.new('Normal')
		self.addItem(i94_mdNormal)
		i94_mdNormal.setIdent('ARC-0084')
		i94_mdNormal.setDescription('')
		i93_vlFull_Range = PORISValueFloat.new('Full_Range',0.0,2048.0,4098.0)
		self.addItem(i93_vlFull_Range)
		i93_vlFull_Range.setIdent('ARC-0083')
		i93_vlFull_Range.setDescription('')
		i95_prCols = PORISParam.new('Cols')
		self.addItem(i95_prCols)
		i95_prCols.setIdent('ARC-0085')
		i95_prCols.setDescription('')
		i100_mdNormal = PORISMode.new('Normal')
		self.addItem(i100_mdNormal)
		i100_mdNormal.setIdent('ARC-0087')
		i100_mdNormal.setDescription('')
		i99_vlFull_Range = PORISValueFloat.new('Full_Range',0.0,2048.0,4098.0)
		self.addItem(i99_vlFull_Range)
		i99_vlFull_Range.setIdent('ARC-0086')
		i99_vlFull_Range.setDescription('')
		i101_proffsetRow = PORISParam.new('offsetRow')
		self.addItem(i101_proffsetRow)
		i101_proffsetRow.setIdent('ARC-0088')
		i101_proffsetRow.setDescription('')
		i106_mdNormal = PORISMode.new('Normal')
		self.addItem(i106_mdNormal)
		i106_mdNormal.setIdent('ARC-0090')
		i106_mdNormal.setDescription('')
		i105_vlFull_Range = PORISValueFloat.new('Full_Range',0.0,2048.0,4098.0)
		self.addItem(i105_vlFull_Range)
		i105_vlFull_Range.setIdent('ARC-0089')
		i105_vlFull_Range.setDescription('')
		i107_proffsetCol = PORISParam.new('offsetCol')
		self.addItem(i107_proffsetCol)
		i107_proffsetCol.setIdent('ARC-0091')
		i107_proffsetCol.setDescription('')
		i112_mdNormal = PORISMode.new('Normal')
		self.addItem(i112_mdNormal)
		i112_mdNormal.setIdent('ARC-0093')
		i112_mdNormal.setDescription('')
		puts("Here!!!-----------------------------------")
		i111_vlFull_Range = PORISValueFloat.new('Full_Range',0.0,2048.0,4098.0)
		self.addItem(i111_vlFull_Range)
		i111_vlFull_Range.setIdent('ARC-0092')
		i111_vlFull_Range.setDescription('')
		self.setRoot(i1_sysARCGenIII)

		i1_sysARCGenIII.addMode(i4_mdReal)
		i1_sysARCGenIII.addMode(i5_mdEmulated)
		i6_sysFirmware.addMode(i9_mdosiris3)
		puts("Here!!!-----------------------------------")
		i6_sysFirmware.addMode(i10_mdtim)
		i6_sysFirmware.addMode(i11_mdosiris2)
		i6_sysFirmware.addMode(i12_mdosiris4)
		i6_sysFirmware.addMode(i13_mdosiris5)
		i14_sysVariants.addMode(i17_mdNormal)
		i14_sysVariants.addMode(i18_mdExtended)
		i14_sysVariants.addMode(i19_mdExtended_2)
		i20_sysAcquisition.addMode(i23_mdNormal)
		i20_sysAcquisition.addMode(i24_mdNormalWindow)
		i20_sysAcquisition.addMode(i25_mdFrameTransfer)
		i20_sysAcquisition.addMode(i26_mdShuffling)
		i20_sysAcquisition.addMode(i27_mdCalibration)
		i55_mdOff.addValue(i51_vl1x1)
		i47_prBinning.addMode(i55_mdOff)
		i56_mdAll.addValue(i51_vl1x1)
		i56_mdAll.addValue(i52_vl1x2)
		i56_mdAll.addValue(i53_vl2x1)
		i56_mdAll.addValue(i54_vl2x2)
		i47_prBinning.addMode(i56_mdAll)
		i57_mdSquare.addValue(i51_vl1x1)
		i57_mdSquare.addValue(i54_vl2x2)
		i47_prBinning.addMode(i57_mdSquare)
		i47_prBinning.addValue(i51_vl1x1)
		i47_prBinning.addValue(i52_vl1x2)
		i47_prBinning.addValue(i53_vl2x1)
		i47_prBinning.addValue(i54_vl2x2)
		i20_sysAcquisition.addParam(i47_prBinning)
		i118_mdNormal.addValue(i117_vlFull_Range)
		i113_prShuffleLines.addMode(i118_mdNormal)
		i113_prShuffleLines.addValue(i117_vlFull_Range)
		i20_sysAcquisition.addParam(i113_prShuffleLines)
		i124_mdNormal.addValue(i123_vlFull_Range)
		i119_prShiftNumber.addMode(i124_mdNormal)
		i119_prShiftNumber.addValue(i123_vlFull_Range)
		i20_sysAcquisition.addParam(i119_prShiftNumber)
		i28_sysDimensions.addMode(i31_mdNormal)
		i28_sysDimensions.addMode(i32_mdFT)
		i38_mdNormal.addValue(i37_vlFull_Range)
		i33_pruiCols.addMode(i38_mdNormal)
		i33_pruiCols.addValue(i37_vlFull_Range)
		i28_sysDimensions.addParam(i33_pruiCols)
		i45_mdNormal.addValue(i43_vlFull_Range)
		i39_pruiRows.addMode(i45_mdNormal)
		i46_mdHalf.addValue(i44_vlFTRange)
		i39_pruiRows.addMode(i46_mdHalf)
		i39_pruiRows.addValue(i43_vlFull_Range)
		i39_pruiRows.addValue(i44_vlFTRange)
		i28_sysDimensions.addParam(i39_pruiRows)
		i20_sysAcquisition.addSubsystem(i28_sysDimensions)
		i58_sysOutputSource.addMode(i61_md0x0)
		i58_sysOutputSource.addMode(i62_md0x1)
		i58_sysOutputSource.addMode(i63_md0x2)
		i58_sysOutputSource.addMode(i64_md0x3)
		i58_sysOutputSource.addMode(i65_mdTWO)
		i58_sysOutputSource.addMode(i66_mdALL)
		i67_sysRecomposition.addMode(i70_mdNone)
		i67_sysRecomposition.addMode(i71_mdSerial)
		i67_sysRecomposition.addMode(i72_mdQuadCCD)
		i67_sysRecomposition.addMode(i73_mdParallel)
		i67_sysRecomposition.addMode(i74_mdQuadIR)
		i67_sysRecomposition.addMode(i75_mdCDSQuad)
		i67_sysRecomposition.addMode(i76_mdHawaiiRG)
		i58_sysOutputSource.addSubsystem(i67_sysRecomposition)
		i20_sysAcquisition.addSubsystem(i58_sysOutputSource)
		i77_sysExposureCtrl.addMode(i80_mdNormal)
		i77_sysExposureCtrl.addMode(i81_mdCalibration)
		i77_sysExposureCtrl.addMode(i82_mdNoShutter)
		i77_sysExposureCtrl.addMode(i83_mdFT)
		i20_sysAcquisition.addSubsystem(i77_sysExposureCtrl)
		i84_sysSubarrayFeature.addMode(i87_mdOff)
		i84_sysSubarrayFeature.addMode(i88_mdOn)
		i94_mdNormal.addValue(i93_vlFull_Range)
		i89_prRows.addMode(i94_mdNormal)
		i89_prRows.addValue(i93_vlFull_Range)
		i84_sysSubarrayFeature.addParam(i89_prRows)
		i100_mdNormal.addValue(i99_vlFull_Range)
		i95_prCols.addMode(i100_mdNormal)
		i95_prCols.addValue(i99_vlFull_Range)
		i84_sysSubarrayFeature.addParam(i95_prCols)
		i106_mdNormal.addValue(i105_vlFull_Range)
		i101_proffsetRow.addMode(i106_mdNormal)
		i101_proffsetRow.addValue(i105_vlFull_Range)
		i84_sysSubarrayFeature.addParam(i101_proffsetRow)
		i112_mdNormal.addValue(i111_vlFull_Range)
		i107_proffsetCol.addMode(i112_mdNormal)
		i107_proffsetCol.addValue(i111_vlFull_Range)
		i84_sysSubarrayFeature.addParam(i107_proffsetCol)
		i20_sysAcquisition.addSubsystem(i84_sysSubarrayFeature)
		i14_sysVariants.addSubsystem(i20_sysAcquisition)
		i6_sysFirmware.addSubsystem(i14_sysVariants)
		i1_sysARCGenIII.addSubsystem(i6_sysFirmware)




		i4_mdReal.addSubMode(i10_mdtim)
		i4_mdReal.addSubMode(i11_mdosiris2)
		i4_mdReal.addSubMode(i9_mdosiris3)
		i4_mdReal.addSubMode(i12_mdosiris4)
		i4_mdReal.addSubMode(i13_mdosiris5)
		i5_mdEmulated.addSubMode(i10_mdtim)
		i5_mdEmulated.addSubMode(i11_mdosiris2)
		i5_mdEmulated.addSubMode(i9_mdosiris3)
		i5_mdEmulated.addSubMode(i12_mdosiris4)
		i5_mdEmulated.addSubMode(i13_mdosiris5)
		i9_mdosiris3.addSubMode(i19_mdExtended_2)
		i10_mdtim.addSubMode(i17_mdNormal)
		i11_mdosiris2.addSubMode(i18_mdExtended)
		i12_mdosiris4.addSubMode(i19_mdExtended_2)
		i13_mdosiris5.addSubMode(i19_mdExtended_2)
		i17_mdNormal.addSubMode(i23_mdNormal)
		i17_mdNormal.addSubMode(i24_mdNormalWindow)
		i18_mdExtended.addSubMode(i23_mdNormal)
		i18_mdExtended.addSubMode(i25_mdFrameTransfer)
		i18_mdExtended.addSubMode(i26_mdShuffling)
		i18_mdExtended.addSubMode(i24_mdNormalWindow)
		i19_mdExtended_2.addSubMode(i26_mdShuffling)
		i19_mdExtended_2.addSubMode(i25_mdFrameTransfer)
		i19_mdExtended_2.addSubMode(i23_mdNormal)
		i19_mdExtended_2.addSubMode(i24_mdNormalWindow)
		i19_mdExtended_2.addSubMode(i27_mdCalibration)
		i23_mdNormal.addSubMode(i87_mdOff)
		i23_mdNormal.addSubMode(i80_mdNormal)
		i23_mdNormal.addSubMode(i61_md0x0)
		i23_mdNormal.addSubMode(i62_md0x1)
		i23_mdNormal.addSubMode(i63_md0x2)
		i23_mdNormal.addSubMode(i64_md0x3)
		i23_mdNormal.addSubMode(i65_mdTWO)
		i23_mdNormal.addSubMode(i66_mdALL)
		i23_mdNormal.addSubMode(i31_mdNormal)
		i23_mdNormal.addSubMode(i56_mdAll)
		i24_mdNormalWindow.addSubMode(i88_mdOn)
		i24_mdNormalWindow.addSubMode(i80_mdNormal)
		i24_mdNormalWindow.addSubMode(i61_md0x0)
		i24_mdNormalWindow.addSubMode(i56_mdAll)
		i25_mdFrameTransfer.addSubMode(i83_mdFT)
		i25_mdFrameTransfer.addSubMode(i65_mdTWO)
		i25_mdFrameTransfer.addSubMode(i32_mdFT)
		i25_mdFrameTransfer.addSubMode(i56_mdAll)
		i25_mdFrameTransfer.addSubMode(i61_md0x0)
		i26_mdShuffling.addSubMode(i118_mdNormal)
		i26_mdShuffling.addSubMode(i124_mdNormal)
		i26_mdShuffling.addSubMode(i61_md0x0)
		i26_mdShuffling.addSubMode(i62_md0x1)
		i26_mdShuffling.addSubMode(i63_md0x2)
		i26_mdShuffling.addSubMode(i64_md0x3)
		i26_mdShuffling.addSubMode(i65_mdTWO)
		i26_mdShuffling.addSubMode(i66_mdALL)
		i26_mdShuffling.addSubMode(i31_mdNormal)
		i26_mdShuffling.addSubMode(i56_mdAll)
		i26_mdShuffling.addSubMode(i82_mdNoShutter)
		i27_mdCalibration.addSubMode(i87_mdOff)
		i27_mdCalibration.addSubMode(i61_md0x0)
		i27_mdCalibration.addSubMode(i62_md0x1)
		i27_mdCalibration.addSubMode(i63_md0x2)
		i27_mdCalibration.addSubMode(i64_md0x3)
		i27_mdCalibration.addSubMode(i65_mdTWO)
		i27_mdCalibration.addSubMode(i66_mdALL)
		i27_mdCalibration.addSubMode(i31_mdNormal)
		i27_mdCalibration.addSubMode(i56_mdAll)
		i27_mdCalibration.addSubMode(i81_mdCalibration)
		i31_mdNormal.addSubMode(i45_mdNormal)
		i31_mdNormal.addSubMode(i38_mdNormal)
		i32_mdFT.addSubMode(i46_mdHalf)
		i32_mdFT.addSubMode(i38_mdNormal)
		i61_md0x0.addSubMode(i70_mdNone)
		i62_md0x1.addSubMode(i70_mdNone)
		i63_md0x2.addSubMode(i70_mdNone)
		i64_md0x3.addSubMode(i70_mdNone)
		i65_mdTWO.addSubMode(i71_mdSerial)
		i66_mdALL.addSubMode(i72_mdQuadCCD)
		i88_mdOn.addSubMode(i94_mdNormal)
		i88_mdOn.addSubMode(i100_mdNormal)
		i88_mdOn.addSubMode(i106_mdNormal)
		i88_mdOn.addSubMode(i112_mdNormal)
	end
end

thismodel = ARCGenIIIPORIS.new(8)

root = thismodel.getRoot
engmode = root.getModeFromName("UNRESTRICTED")
puts(engmode.getName)
puts(engmode.class.name)
puts(engmode.getSubModes.length.to_s)

xmlmodel = thismodel.toXML
puts(xmlmodel.to_s)
