=begin
------- Constructor code --------
=end
require_relative 'PORIS'

class ARCGenIIIPORIS < PORISDoc
	def initialize(project_id)
		super(project_id)
		i1_sysARCGenIII = PORISSys.new('ARCGenIII')
		self.addItem(i1_sysARCGenIII)
		i1_sysARCGenIII.setIdent('ARC-0004')
		i1_sysARCGenIII.setDescription('')
		i82_mdARCGenIIIMode_Real = PORISMode.new('ARCGenIIIMode_Real')
		self.addItem(i82_mdARCGenIIIMode_Real)
		i82_mdARCGenIIIMode_Real.setIdent('ARC-0018')
		i82_mdARCGenIIIMode_Real.setDescription('')
		i83_mdARCGenIIIMode_Emulated = PORISMode.new('ARCGenIIIMode_Emulated')
		self.addItem(i83_mdARCGenIIIMode_Emulated)
		i83_mdARCGenIIIMode_Emulated.setIdent('ARC-0110')
		i83_mdARCGenIIIMode_Emulated.setDescription('')
		i156_mdARCGenIIIMode_Engineering = PORISMode.new('ARCGenIIIMode_Engineering')
		self.addItem(i156_mdARCGenIIIMode_Engineering)
		i156_mdARCGenIIIMode_Engineering.setIdent('ENG-14')
		i156_mdARCGenIIIMode_Engineering.setDescription('ARCGenIII engineering mode')
		i4_sysFirmware = PORISSys.new('Firmware')
		self.addItem(i4_sysFirmware)
		i4_sysFirmware.setIdent('ARC-0007')
		i4_sysFirmware.setDescription('')
		i84_mdFirmwareMode_tim = PORISMode.new('FirmwareMode_tim')
		self.addItem(i84_mdFirmwareMode_tim)
		i84_mdFirmwareMode_tim.setIdent('ARC-0021')
		i84_mdFirmwareMode_tim.setDescription('')
		i85_mdFirmwareMode_osiris2 = PORISMode.new('FirmwareMode_osiris2')
		self.addItem(i85_mdFirmwareMode_osiris2)
		i85_mdFirmwareMode_osiris2.setIdent('ARC-0062')
		i85_mdFirmwareMode_osiris2.setDescription('')
		i86_mdFirmwareMode_osiris3 = PORISMode.new('FirmwareMode_osiris3')
		self.addItem(i86_mdFirmwareMode_osiris3)
		i86_mdFirmwareMode_osiris3.setIdent('ARC-0073')
		i86_mdFirmwareMode_osiris3.setDescription('')
		i87_mdFirmwareMode_osiris4 = PORISMode.new('FirmwareMode_osiris4')
		self.addItem(i87_mdFirmwareMode_osiris4)
		i87_mdFirmwareMode_osiris4.setIdent('ARC-0074')
		i87_mdFirmwareMode_osiris4.setDescription('')
		i88_mdFirmwareMode_osiris5 = PORISMode.new('FirmwareMode_osiris5')
		self.addItem(i88_mdFirmwareMode_osiris5)
		i88_mdFirmwareMode_osiris5.setIdent('ARC-0075')
		i88_mdFirmwareMode_osiris5.setDescription('')
		i157_mdFirmwareMode_Engineering = PORISMode.new('FirmwareMode_Engineering')
		self.addItem(i157_mdFirmwareMode_Engineering)
		i157_mdFirmwareMode_Engineering.setIdent('ENG-15')
		i157_mdFirmwareMode_Engineering.setDescription('Firmware engineering mode')
		i7_sysVariants = PORISSys.new('Variants')
		self.addItem(i7_sysVariants)
		i7_sysVariants.setIdent('ARC-0097')
		i7_sysVariants.setDescription('')
		i153_mdVariantsMode_Normal = PORISMode.new('VariantsMode_Normal')
		self.addItem(i153_mdVariantsMode_Normal)
		i153_mdVariantsMode_Normal.setIdent('ARC-0098')
		i153_mdVariantsMode_Normal.setDescription('')
		i154_mdVariantsMode_Extended = PORISMode.new('VariantsMode_Extended')
		self.addItem(i154_mdVariantsMode_Extended)
		i154_mdVariantsMode_Extended.setIdent('ARC-0105')
		i154_mdVariantsMode_Extended.setDescription('')
		i155_mdVariantsMode_Extended_2 = PORISMode.new('VariantsMode_Extended_2')
		self.addItem(i155_mdVariantsMode_Extended_2)
		i155_mdVariantsMode_Extended_2.setIdent('ARC-0138')
		i155_mdVariantsMode_Extended_2.setDescription('')
		i158_mdVariantsMode_Engineering = PORISMode.new('VariantsMode_Engineering')
		self.addItem(i158_mdVariantsMode_Engineering)
		i158_mdVariantsMode_Engineering.setIdent('ENG-16')
		i158_mdVariantsMode_Engineering.setDescription('Variants engineering mode')
		i10_sysAcquisition = PORISSys.new('Acquisition')
		self.addItem(i10_sysAcquisition)
		i10_sysAcquisition.setIdent('ARC-0076')
		i10_sysAcquisition.setDescription('')
		i89_mdAcquisitionMode_Normal = PORISMode.new('AcquisitionMode_Normal')
		self.addItem(i89_mdAcquisitionMode_Normal)
		i89_mdAcquisitionMode_Normal.setIdent('ARC-0077')
		i89_mdAcquisitionMode_Normal.setDescription('')
		i90_mdAcquisitionMode_FrameTransfer = PORISMode.new('AcquisitionMode_FrameTransfer')
		self.addItem(i90_mdAcquisitionMode_FrameTransfer)
		i90_mdAcquisitionMode_FrameTransfer.setIdent('ARC-0078')
		i90_mdAcquisitionMode_FrameTransfer.setDescription('')
		i91_mdAcquisitionMode_Shuffling = PORISMode.new('AcquisitionMode_Shuffling')
		self.addItem(i91_mdAcquisitionMode_Shuffling)
		i91_mdAcquisitionMode_Shuffling.setIdent('ARC-0079')
		i91_mdAcquisitionMode_Shuffling.setDescription('')
		i138_mdAcquisitionMode_NormalWindow = PORISMode.new('AcquisitionMode_NormalWindow')
		self.addItem(i138_mdAcquisitionMode_NormalWindow)
		i138_mdAcquisitionMode_NormalWindow.setIdent('ARC-0126')
		i138_mdAcquisitionMode_NormalWindow.setDescription('')
		i152_mdAcquisitionMode_Calibration = PORISMode.new('AcquisitionMode_Calibration')
		self.addItem(i152_mdAcquisitionMode_Calibration)
		i152_mdAcquisitionMode_Calibration.setIdent('ARC-0137')
		i152_mdAcquisitionMode_Calibration.setDescription('')
		i159_mdAcquisitionMode_Engineering = PORISMode.new('AcquisitionMode_Engineering')
		self.addItem(i159_mdAcquisitionMode_Engineering)
		i159_mdAcquisitionMode_Engineering.setIdent('ENG-17')
		i159_mdAcquisitionMode_Engineering.setDescription('Acquisition engineering mode')
		i13_prShuffleLines = PORISParam.new('ShuffleLines')
		self.addItem(i13_prShuffleLines)
		i13_prShuffleLines.setIdent('ARC-0080')
		i13_prShuffleLines.setDescription('')
		i93_mdShuffleLinesMode_Normal = PORISMode.new('ShuffleLinesMode_Normal')
		self.addItem(i93_mdShuffleLinesMode_Normal)
		i93_mdShuffleLinesMode_Normal.setIdent('ARC-0082')
		i93_mdShuffleLinesMode_Normal.setDescription('')
		i92_vlShuffleLines_Full_Range = PORISValueFloat.new('ShuffleLines_Full_Range',0,200,1000)
		self.addItem(i92_vlShuffleLines_Full_Range)
		i92_vlShuffleLines_Full_Range.setIdent('ARC-0081')
		i92_vlShuffleLines_Full_Range.setDescription('')
		i17_prShiftNumber = PORISParam.new('ShiftNumber')
		self.addItem(i17_prShiftNumber)
		i17_prShiftNumber.setIdent('ARC-0083')
		i17_prShiftNumber.setDescription('')
		i95_mdShiftNumberMode_Normal = PORISMode.new('ShiftNumberMode_Normal')
		self.addItem(i95_mdShiftNumberMode_Normal)
		i95_mdShiftNumberMode_Normal.setIdent('ARC-0085')
		i95_mdShiftNumberMode_Normal.setDescription('')
		i94_vlShiftNumber_Full_Range = PORISValueFloat.new('ShiftNumber_Full_Range',0,5,1000)
		self.addItem(i94_vlShiftNumber_Full_Range)
		i94_vlShiftNumber_Full_Range.setIdent('ARC-0084')
		i94_vlShiftNumber_Full_Range.setDescription('')
		i78_prBinning = PORISParam.new('Binning')
		self.addItem(i78_prBinning)
		i78_prBinning.setIdent('ARC-0008')
		i78_prBinning.setDescription('')
		i151_mdBinningMode_All = PORISMode.new('BinningMode_All')
		self.addItem(i151_mdBinningMode_All)
		i151_mdBinningMode_All.setIdent('ARC-0031')
		i151_mdBinningMode_All.setDescription('')
		i147_vlBinning_1x1 = PORISValue.new('Binning_1x1')
		self.addItem(i147_vlBinning_1x1)
		i147_vlBinning_1x1.setIdent('ARC-0026')
		i147_vlBinning_1x1.setDescription('')
		i148_vlBinning_1x2 = PORISValue.new('Binning_1x2')
		self.addItem(i148_vlBinning_1x2)
		i148_vlBinning_1x2.setIdent('ARC-0027')
		i148_vlBinning_1x2.setDescription('')
		i149_vlBinning_2x1 = PORISValue.new('Binning_2x1')
		self.addItem(i149_vlBinning_2x1)
		i149_vlBinning_2x1.setIdent('ARC-0028')
		i149_vlBinning_2x1.setDescription('')
		i150_vlBinning_2x2 = PORISValue.new('Binning_2x2')
		self.addItem(i150_vlBinning_2x2)
		i150_vlBinning_2x2.setIdent('ARC-0029')
		i150_vlBinning_2x2.setDescription('')
		i21_sysSubarrayFeature = PORISSys.new('SubarrayFeature')
		self.addItem(i21_sysSubarrayFeature)
		i21_sysSubarrayFeature.setIdent('ARC-0013')
		i21_sysSubarrayFeature.setDescription('')
		i96_mdSubarrayFeatureMode_Off = PORISMode.new('SubarrayFeatureMode_Off')
		self.addItem(i96_mdSubarrayFeatureMode_Off)
		i96_mdSubarrayFeatureMode_Off.setIdent('ARC-0041')
		i96_mdSubarrayFeatureMode_Off.setDescription('')
		i97_mdSubarrayFeatureMode_On = PORISMode.new('SubarrayFeatureMode_On')
		self.addItem(i97_mdSubarrayFeatureMode_On)
		i97_mdSubarrayFeatureMode_On.setIdent('ARC-0042')
		i97_mdSubarrayFeatureMode_On.setDescription('')
		i160_mdSubarrayFeatureMode_Engineering = PORISMode.new('SubarrayFeatureMode_Engineering')
		self.addItem(i160_mdSubarrayFeatureMode_Engineering)
		i160_mdSubarrayFeatureMode_Engineering.setIdent('ENG-18')
		i160_mdSubarrayFeatureMode_Engineering.setDescription('SubarrayFeature engineering mode')
		i24_prCols = PORISParam.new('Cols')
		self.addItem(i24_prCols)
		i24_prCols.setIdent('ARC-0044')
		i24_prCols.setDescription('')
		i98_mdColsMode_Normal = PORISMode.new('ColsMode_Normal')
		self.addItem(i98_mdColsMode_Normal)
		i98_mdColsMode_Normal.setIdent('ARC-0066')
		i98_mdColsMode_Normal.setDescription('')
		i99_vlCols_Full_Range = PORISValueFloat.new('Cols_Full_Range',0,2048,4098)
		self.addItem(i99_vlCols_Full_Range)
		i99_vlCols_Full_Range.setIdent('ARC-0065')
		i99_vlCols_Full_Range.setDescription('')
		i28_proffsetRow = PORISParam.new('offsetRow')
		self.addItem(i28_proffsetRow)
		i28_proffsetRow.setIdent('ARC-0045')
		i28_proffsetRow.setDescription('')
		i100_mdoffsetRowMode_Normal = PORISMode.new('offsetRowMode_Normal')
		self.addItem(i100_mdoffsetRowMode_Normal)
		i100_mdoffsetRowMode_Normal.setIdent('ARC-0068')
		i100_mdoffsetRowMode_Normal.setDescription('')
		i101_vloffsetRow_Full_Range = PORISValueFloat.new('offsetRow_Full_Range',0,2048,4098)
		self.addItem(i101_vloffsetRow_Full_Range)
		i101_vloffsetRow_Full_Range.setIdent('ARC-0067')
		i101_vloffsetRow_Full_Range.setDescription('')
		i32_prRows = PORISParam.new('Rows')
		self.addItem(i32_prRows)
		i32_prRows.setIdent('ARC-0043')
		i32_prRows.setDescription('')
		i102_mdRowsMode_Normal = PORISMode.new('RowsMode_Normal')
		self.addItem(i102_mdRowsMode_Normal)
		i102_mdRowsMode_Normal.setIdent('ARC-0064')
		i102_mdRowsMode_Normal.setDescription('')
		i103_vlRows_Full_Range = PORISValueFloat.new('Rows_Full_Range',0,2048,4098)
		self.addItem(i103_vlRows_Full_Range)
		i103_vlRows_Full_Range.setIdent('ARC-0063')
		i103_vlRows_Full_Range.setDescription('')
		i36_proffsetCol = PORISParam.new('offsetCol')
		self.addItem(i36_proffsetCol)
		i36_proffsetCol.setIdent('ARC-0046')
		i36_proffsetCol.setDescription('')
		i104_mdoffsetColMode_Normal = PORISMode.new('offsetColMode_Normal')
		self.addItem(i104_mdoffsetColMode_Normal)
		i104_mdoffsetColMode_Normal.setIdent('ARC-0070')
		i104_mdoffsetColMode_Normal.setDescription('')
		i105_vloffsetCol_Full_Range = PORISValueFloat.new('offsetCol_Full_Range',0,2048,4098)
		self.addItem(i105_vloffsetCol_Full_Range)
		i105_vloffsetCol_Full_Range.setIdent('ARC-0069')
		i105_vloffsetCol_Full_Range.setDescription('')
		i40_sysExposureCtrl = PORISSys.new('ExposureCtrl')
		self.addItem(i40_sysExposureCtrl)
		i40_sysExposureCtrl.setIdent('ARC-0103')
		i40_sysExposureCtrl.setDescription('')
		i115_mdExposureCtrlMode_Normal = PORISMode.new('ExposureCtrlMode_Normal')
		self.addItem(i115_mdExposureCtrlMode_Normal)
		i115_mdExposureCtrlMode_Normal.setIdent('ARC-0104')
		i115_mdExposureCtrlMode_Normal.setDescription('')
		i116_mdExposureCtrlMode_FT = PORISMode.new('ExposureCtrlMode_FT')
		self.addItem(i116_mdExposureCtrlMode_FT)
		i116_mdExposureCtrlMode_FT.setIdent('ARC-0114')
		i116_mdExposureCtrlMode_FT.setDescription('')
		i123_mdExposureCtrlMode_NoShutter = PORISMode.new('ExposureCtrlMode_NoShutter')
		self.addItem(i123_mdExposureCtrlMode_NoShutter)
		i123_mdExposureCtrlMode_NoShutter.setIdent('ARC-0134')
		i123_mdExposureCtrlMode_NoShutter.setDescription('')
		i124_mdExposureCtrlMode_Calibration = PORISMode.new('ExposureCtrlMode_Calibration')
		self.addItem(i124_mdExposureCtrlMode_Calibration)
		i124_mdExposureCtrlMode_Calibration.setIdent('ARC-0136')
		i124_mdExposureCtrlMode_Calibration.setDescription('')
		i161_mdExposureCtrlMode_Engineering = PORISMode.new('ExposureCtrlMode_Engineering')
		self.addItem(i161_mdExposureCtrlMode_Engineering)
		i161_mdExposureCtrlMode_Engineering.setIdent('ENG-19')
		i161_mdExposureCtrlMode_Engineering.setDescription('ExposureCtrl engineering mode')
		i46_prExpTime = PORISParam.new('ExpTime')
		self.addItem(i46_prExpTime)
		i46_prExpTime.setIdent('ARC-0010')
		i46_prExpTime.setDescription('')
		i109_mdExpTimeMode_Normal = PORISMode.new('ExpTimeMode_Normal')
		self.addItem(i109_mdExpTimeMode_Normal)
		i109_mdExpTimeMode_Normal.setIdent('ARC-0036')
		i109_mdExpTimeMode_Normal.setDescription('')
		i110_mdExpTimeMode_FT = PORISMode.new('ExpTimeMode_FT')
		self.addItem(i110_mdExpTimeMode_FT)
		i110_mdExpTimeMode_FT.setIdent('ARC-0119')
		i110_mdExpTimeMode_FT.setDescription('')
		i108_vlExpTime_Full_Range = PORISValueFloat.new('ExpTime_Full_Range',0,1,4294967.295)
		self.addItem(i108_vlExpTime_Full_Range)
		i108_vlExpTime_Full_Range.setIdent('ARC-0035')
		i108_vlExpTime_Full_Range.setDescription('')
		i111_vlExpTime_FT_Range = PORISValueFloat.new('ExpTime_FT_Range',0,0,360)
		self.addItem(i111_vlExpTime_FT_Range)
		i111_vlExpTime_FT_Range.setIdent('ARC-0120')
		i111_vlExpTime_FT_Range.setDescription('')
		i53_prnumOfFrames = PORISParam.new('numOfFrames')
		self.addItem(i53_prnumOfFrames)
		i53_prnumOfFrames.setIdent('ARC-0001')
		i53_prnumOfFrames.setDescription('')
		i117_mdnumOfFramesMode_Multiple = PORISMode.new('numOfFramesMode_Multiple')
		self.addItem(i117_mdnumOfFramesMode_Multiple)
		i117_mdnumOfFramesMode_Multiple.setIdent('ARC-0072')
		i117_mdnumOfFramesMode_Multiple.setDescription('')
		i119_mdnumOfFramesMode_Single = PORISMode.new('numOfFramesMode_Single')
		self.addItem(i119_mdnumOfFramesMode_Single)
		i119_mdnumOfFramesMode_Single.setIdent('ARC-0037')
		i119_mdnumOfFramesMode_Single.setDescription('')
		i118_vlnumOfFrames_Multiple_Range = PORISValueFloat.new('numOfFrames_Multiple_Range',2,10,4294967295)
		self.addItem(i118_vlnumOfFrames_Multiple_Range)
		i118_vlnumOfFrames_Multiple_Range.setIdent('ARC-0071')
		i118_vlnumOfFrames_Multiple_Range.setDescription('')
		i120_vlnumOfFrames_1 = PORISValue.new('numOfFrames_1')
		self.addItem(i120_vlnumOfFrames_1)
		i120_vlnumOfFrames_1.setIdent('ARC-0131')
		i120_vlnumOfFrames_1.setDescription('')
		i57_prCalibGain = PORISParam.new('CalibGain')
		self.addItem(i57_prCalibGain)
		i57_prCalibGain.setIdent('ARC-0130')
		i57_prCalibGain.setDescription('')
		i122_mdCalibGainMode_Normal = PORISMode.new('CalibGainMode_Normal')
		self.addItem(i122_mdCalibGainMode_Normal)
		i122_mdCalibGainMode_Normal.setIdent('ARC-0125')
		i122_mdCalibGainMode_Normal.setDescription('')
		i121_vlCalibGain_Normal_Range = PORISValueFloat.new('CalibGain_Normal_Range',0,2,15)
		self.addItem(i121_vlCalibGain_Normal_Range)
		i121_vlCalibGain_Normal_Range.setIdent('ARC-0124')
		i121_vlCalibGain_Normal_Range.setDescription('')
		i43_sysOpenShutter = PORISSys.new('OpenShutter')
		self.addItem(i43_sysOpenShutter)
		i43_sysOpenShutter.setIdent('ARC-0009')
		i43_sysOpenShutter.setDescription('')
		i106_mdOpenShutterMode_On = PORISMode.new('OpenShutterMode_On')
		self.addItem(i106_mdOpenShutterMode_On)
		i106_mdOpenShutterMode_On.setIdent('ARC-0033')
		i106_mdOpenShutterMode_On.setDescription('')
		i107_mdOpenShutterMode_Off = PORISMode.new('OpenShutterMode_Off')
		self.addItem(i107_mdOpenShutterMode_Off)
		i107_mdOpenShutterMode_Off.setIdent('ARC-0034')
		i107_mdOpenShutterMode_Off.setDescription('')
		i50_sysPixelSpeed = PORISSys.new('PixelSpeed')
		self.addItem(i50_sysPixelSpeed)
		i50_sysPixelSpeed.setIdent('ARC-0093')
		i50_sysPixelSpeed.setDescription('')
		i112_mdPixelSpeedMode_SLW = PORISMode.new('PixelSpeedMode_SLW')
		self.addItem(i112_mdPixelSpeedMode_SLW)
		i112_mdPixelSpeedMode_SLW.setIdent('ARC-0094')
		i112_mdPixelSpeedMode_SLW.setDescription('')
		i113_mdPixelSpeedMode_MED = PORISMode.new('PixelSpeedMode_MED')
		self.addItem(i113_mdPixelSpeedMode_MED)
		i113_mdPixelSpeedMode_MED.setIdent('ARC-0095')
		i113_mdPixelSpeedMode_MED.setDescription('')
		i114_mdPixelSpeedMode_FST = PORISMode.new('PixelSpeedMode_FST')
		self.addItem(i114_mdPixelSpeedMode_FST)
		i114_mdPixelSpeedMode_FST.setIdent('ARC-0096')
		i114_mdPixelSpeedMode_FST.setDescription('')
		i61_sysOutputSource = PORISSys.new('OutputSource')
		self.addItem(i61_sysOutputSource)
		i61_sysOutputSource.setIdent('ARC-0086')
		i61_sysOutputSource.setDescription('')
		i125_mdOutputSourceMode_0x0 = PORISMode.new('OutputSourceMode_0x0')
		self.addItem(i125_mdOutputSourceMode_0x0)
		i125_mdOutputSourceMode_0x0.setIdent('ARC-0087')
		i125_mdOutputSourceMode_0x0.setDescription('')
		i126_mdOutputSourceMode_0x1 = PORISMode.new('OutputSourceMode_0x1')
		self.addItem(i126_mdOutputSourceMode_0x1)
		i126_mdOutputSourceMode_0x1.setIdent('ARC-0088')
		i126_mdOutputSourceMode_0x1.setDescription('')
		i127_mdOutputSourceMode_0x2 = PORISMode.new('OutputSourceMode_0x2')
		self.addItem(i127_mdOutputSourceMode_0x2)
		i127_mdOutputSourceMode_0x2.setIdent('ARC-0089')
		i127_mdOutputSourceMode_0x2.setDescription('')
		i128_mdOutputSourceMode_0x3 = PORISMode.new('OutputSourceMode_0x3')
		self.addItem(i128_mdOutputSourceMode_0x3)
		i128_mdOutputSourceMode_0x3.setIdent('ARC-0090')
		i128_mdOutputSourceMode_0x3.setDescription('')
		i129_mdOutputSourceMode_ALL = PORISMode.new('OutputSourceMode_ALL')
		self.addItem(i129_mdOutputSourceMode_ALL)
		i129_mdOutputSourceMode_ALL.setIdent('ARC-0091')
		i129_mdOutputSourceMode_ALL.setDescription('')
		i130_mdOutputSourceMode_TWO = PORISMode.new('OutputSourceMode_TWO')
		self.addItem(i130_mdOutputSourceMode_TWO)
		i130_mdOutputSourceMode_TWO.setIdent('ARC-0092')
		i130_mdOutputSourceMode_TWO.setDescription('')
		i162_mdOutputSourceMode_Engineering = PORISMode.new('OutputSourceMode_Engineering')
		self.addItem(i162_mdOutputSourceMode_Engineering)
		i162_mdOutputSourceMode_Engineering.setIdent('ENG-22')
		i162_mdOutputSourceMode_Engineering.setDescription('OutputSource engineering mode')
		i64_sysRecomposition = PORISSys.new('Recomposition')
		self.addItem(i64_sysRecomposition)
		i64_sysRecomposition.setIdent('ARC-0020')
		i64_sysRecomposition.setDescription('')
		i131_mdRecompositionMode_None = PORISMode.new('RecompositionMode_None')
		self.addItem(i131_mdRecompositionMode_None)
		i131_mdRecompositionMode_None.setIdent('ARC-0055')
		i131_mdRecompositionMode_None.setDescription('')
		i132_mdRecompositionMode_Parallel = PORISMode.new('RecompositionMode_Parallel')
		self.addItem(i132_mdRecompositionMode_Parallel)
		i132_mdRecompositionMode_Parallel.setIdent('ARC-0056')
		i132_mdRecompositionMode_Parallel.setDescription('')
		i133_mdRecompositionMode_Serial = PORISMode.new('RecompositionMode_Serial')
		self.addItem(i133_mdRecompositionMode_Serial)
		i133_mdRecompositionMode_Serial.setIdent('ARC-0057')
		i133_mdRecompositionMode_Serial.setDescription('')
		i134_mdRecompositionMode_QuadCCD = PORISMode.new('RecompositionMode_QuadCCD')
		self.addItem(i134_mdRecompositionMode_QuadCCD)
		i134_mdRecompositionMode_QuadCCD.setIdent('ARC-0058')
		i134_mdRecompositionMode_QuadCCD.setDescription('')
		i135_mdRecompositionMode_QuadIR = PORISMode.new('RecompositionMode_QuadIR')
		self.addItem(i135_mdRecompositionMode_QuadIR)
		i135_mdRecompositionMode_QuadIR.setIdent('ARC-0059')
		i135_mdRecompositionMode_QuadIR.setDescription('')
		i136_mdRecompositionMode_CDSQuad = PORISMode.new('RecompositionMode_CDSQuad')
		self.addItem(i136_mdRecompositionMode_CDSQuad)
		i136_mdRecompositionMode_CDSQuad.setIdent('ARC-0060')
		i136_mdRecompositionMode_CDSQuad.setDescription('')
		i137_mdRecompositionMode_HawaiiRG = PORISMode.new('RecompositionMode_HawaiiRG')
		self.addItem(i137_mdRecompositionMode_HawaiiRG)
		i137_mdRecompositionMode_HawaiiRG.setIdent('ARC-0061')
		i137_mdRecompositionMode_HawaiiRG.setDescription('')
		i67_sysDimensions = PORISSys.new('Dimensions')
		self.addItem(i67_sysDimensions)
		i67_sysDimensions.setIdent('ARC-0099')
		i67_sysDimensions.setDescription('')
		i145_mdDimensionsMode_Normal = PORISMode.new('DimensionsMode_Normal')
		self.addItem(i145_mdDimensionsMode_Normal)
		i145_mdDimensionsMode_Normal.setIdent('ARC-0100')
		i145_mdDimensionsMode_Normal.setDescription('')
		i146_mdDimensionsMode_FT = PORISMode.new('DimensionsMode_FT')
		self.addItem(i146_mdDimensionsMode_FT)
		i146_mdDimensionsMode_FT.setIdent('ARC-0129')
		i146_mdDimensionsMode_FT.setDescription('')
		i163_mdDimensionsMode_Engineering = PORISMode.new('DimensionsMode_Engineering')
		self.addItem(i163_mdDimensionsMode_Engineering)
		i163_mdDimensionsMode_Engineering.setIdent('ENG-24')
		i163_mdDimensionsMode_Engineering.setDescription('Dimensions engineering mode')
		i70_pruiRows = PORISParam.new('uiRows')
		self.addItem(i70_pruiRows)
		i70_pruiRows.setIdent('ARC-0005')
		i70_pruiRows.setDescription('')
		i140_mduiRowsMode_Normal = PORISMode.new('uiRowsMode_Normal')
		self.addItem(i140_mduiRowsMode_Normal)
		i140_mduiRowsMode_Normal.setIdent('ARC-0023')
		i140_mduiRowsMode_Normal.setDescription('')
		i142_mduiRowsMode_Half = PORISMode.new('uiRowsMode_Half')
		self.addItem(i142_mduiRowsMode_Half)
		i142_mduiRowsMode_Half.setIdent('ARC-0128')
		i142_mduiRowsMode_Half.setDescription('')
		i139_vluiRows_Full_Range = PORISValueFloat.new('uiRows_Full_Range',0,4112,4112)
		self.addItem(i139_vluiRows_Full_Range)
		i139_vluiRows_Full_Range.setIdent('ARC-0022')
		i139_vluiRows_Full_Range.setDescription('')
		i141_vluiRows_FTRange = PORISValueFloat.new('uiRows_FTRange',0,2056,2056)
		self.addItem(i141_vluiRows_FTRange)
		i141_vluiRows_FTRange.setIdent('ARC-0127')
		i141_vluiRows_FTRange.setDescription('')
		i74_pruiCols = PORISParam.new('uiCols')
		self.addItem(i74_pruiCols)
		i74_pruiCols.setIdent('ARC-0006')
		i74_pruiCols.setDescription('')
		i144_mduiColsMode_Normal = PORISMode.new('uiColsMode_Normal')
		self.addItem(i144_mduiColsMode_Normal)
		i144_mduiColsMode_Normal.setIdent('ARC-0025')
		i144_mduiColsMode_Normal.setDescription('')
		i143_vluiCols_Full_Range = PORISValueFloat.new('uiCols_Full_Range',0,4096,4096)
		self.addItem(i143_vluiCols_Full_Range)
		i143_vluiCols_Full_Range.setIdent('ARC-0024')
		i143_vluiCols_Full_Range.setDescription('')
		self.setRoot(i1_sysARCGenIII)
		i82_mdARCGenIIIMode_Real.addSubMode(i84_mdFirmwareMode_tim)
		i82_mdARCGenIIIMode_Real.addSubMode(i85_mdFirmwareMode_osiris2)
		i82_mdARCGenIIIMode_Real.addSubMode(i86_mdFirmwareMode_osiris3)
		i82_mdARCGenIIIMode_Real.addSubMode(i87_mdFirmwareMode_osiris4)
		i82_mdARCGenIIIMode_Real.addSubMode(i88_mdFirmwareMode_osiris5)
		i1_sysARCGenIII.addMode(i82_mdARCGenIIIMode_Real)
		i83_mdARCGenIIIMode_Emulated.addSubMode(i84_mdFirmwareMode_tim)
		i83_mdARCGenIIIMode_Emulated.addSubMode(i85_mdFirmwareMode_osiris2)
		i83_mdARCGenIIIMode_Emulated.addSubMode(i86_mdFirmwareMode_osiris3)
		i83_mdARCGenIIIMode_Emulated.addSubMode(i87_mdFirmwareMode_osiris4)
		i83_mdARCGenIIIMode_Emulated.addSubMode(i88_mdFirmwareMode_osiris5)
		i1_sysARCGenIII.addMode(i83_mdARCGenIIIMode_Emulated)
		i156_mdARCGenIIIMode_Engineering.addSubMode(i84_mdFirmwareMode_tim)
		i156_mdARCGenIIIMode_Engineering.addSubMode(i85_mdFirmwareMode_osiris2)
		i156_mdARCGenIIIMode_Engineering.addSubMode(i86_mdFirmwareMode_osiris3)
		i156_mdARCGenIIIMode_Engineering.addSubMode(i87_mdFirmwareMode_osiris4)
		i156_mdARCGenIIIMode_Engineering.addSubMode(i88_mdFirmwareMode_osiris5)
		i156_mdARCGenIIIMode_Engineering.addSubMode(i157_mdFirmwareMode_Engineering)
		i1_sysARCGenIII.addMode(i156_mdARCGenIIIMode_Engineering)
		i84_mdFirmwareMode_tim.addSubMode(i153_mdVariantsMode_Normal)
		i4_sysFirmware.addMode(i84_mdFirmwareMode_tim)
		i85_mdFirmwareMode_osiris2.addSubMode(i154_mdVariantsMode_Extended)
		i4_sysFirmware.addMode(i85_mdFirmwareMode_osiris2)
		i86_mdFirmwareMode_osiris3.addSubMode(i155_mdVariantsMode_Extended_2)
		i4_sysFirmware.addMode(i86_mdFirmwareMode_osiris3)
		i87_mdFirmwareMode_osiris4.addSubMode(i155_mdVariantsMode_Extended_2)
		i4_sysFirmware.addMode(i87_mdFirmwareMode_osiris4)
		i88_mdFirmwareMode_osiris5.addSubMode(i155_mdVariantsMode_Extended_2)
		i4_sysFirmware.addMode(i88_mdFirmwareMode_osiris5)
		i157_mdFirmwareMode_Engineering.addSubMode(i153_mdVariantsMode_Normal)
		i157_mdFirmwareMode_Engineering.addSubMode(i154_mdVariantsMode_Extended)
		i157_mdFirmwareMode_Engineering.addSubMode(i155_mdVariantsMode_Extended_2)
		i157_mdFirmwareMode_Engineering.addSubMode(i158_mdVariantsMode_Engineering)
		i4_sysFirmware.addMode(i157_mdFirmwareMode_Engineering)
		i153_mdVariantsMode_Normal.addSubMode(i89_mdAcquisitionMode_Normal)
		i153_mdVariantsMode_Normal.addSubMode(i138_mdAcquisitionMode_NormalWindow)
		i7_sysVariants.addMode(i153_mdVariantsMode_Normal)
		i154_mdVariantsMode_Extended.addSubMode(i91_mdAcquisitionMode_Shuffling)
		i154_mdVariantsMode_Extended.addSubMode(i90_mdAcquisitionMode_FrameTransfer)
		i154_mdVariantsMode_Extended.addSubMode(i89_mdAcquisitionMode_Normal)
		i154_mdVariantsMode_Extended.addSubMode(i138_mdAcquisitionMode_NormalWindow)
		i7_sysVariants.addMode(i154_mdVariantsMode_Extended)
		i155_mdVariantsMode_Extended_2.addSubMode(i91_mdAcquisitionMode_Shuffling)
		i155_mdVariantsMode_Extended_2.addSubMode(i90_mdAcquisitionMode_FrameTransfer)
		i155_mdVariantsMode_Extended_2.addSubMode(i89_mdAcquisitionMode_Normal)
		i155_mdVariantsMode_Extended_2.addSubMode(i138_mdAcquisitionMode_NormalWindow)
		i155_mdVariantsMode_Extended_2.addSubMode(i152_mdAcquisitionMode_Calibration)
		i7_sysVariants.addMode(i155_mdVariantsMode_Extended_2)
		i158_mdVariantsMode_Engineering.addSubMode(i89_mdAcquisitionMode_Normal)
		i158_mdVariantsMode_Engineering.addSubMode(i90_mdAcquisitionMode_FrameTransfer)
		i158_mdVariantsMode_Engineering.addSubMode(i91_mdAcquisitionMode_Shuffling)
		i158_mdVariantsMode_Engineering.addSubMode(i138_mdAcquisitionMode_NormalWindow)
		i158_mdVariantsMode_Engineering.addSubMode(i152_mdAcquisitionMode_Calibration)
		i158_mdVariantsMode_Engineering.addSubMode(i159_mdAcquisitionMode_Engineering)
		i7_sysVariants.addMode(i158_mdVariantsMode_Engineering)
		i89_mdAcquisitionMode_Normal.addSubMode(i96_mdSubarrayFeatureMode_Off)
		i89_mdAcquisitionMode_Normal.addSubMode(i115_mdExposureCtrlMode_Normal)
		i89_mdAcquisitionMode_Normal.addSubMode(i125_mdOutputSourceMode_0x0)
		i89_mdAcquisitionMode_Normal.addSubMode(i126_mdOutputSourceMode_0x1)
		i89_mdAcquisitionMode_Normal.addSubMode(i127_mdOutputSourceMode_0x2)
		i89_mdAcquisitionMode_Normal.addSubMode(i128_mdOutputSourceMode_0x3)
		i89_mdAcquisitionMode_Normal.addSubMode(i130_mdOutputSourceMode_TWO)
		i89_mdAcquisitionMode_Normal.addSubMode(i129_mdOutputSourceMode_ALL)
		i89_mdAcquisitionMode_Normal.addSubMode(i145_mdDimensionsMode_Normal)
		i89_mdAcquisitionMode_Normal.addSubMode(i151_mdBinningMode_All)
		i10_sysAcquisition.addMode(i89_mdAcquisitionMode_Normal)
		i90_mdAcquisitionMode_FrameTransfer.addSubMode(i116_mdExposureCtrlMode_FT)
		i90_mdAcquisitionMode_FrameTransfer.addSubMode(i130_mdOutputSourceMode_TWO)
		i90_mdAcquisitionMode_FrameTransfer.addSubMode(i125_mdOutputSourceMode_0x0)
		i90_mdAcquisitionMode_FrameTransfer.addSubMode(i146_mdDimensionsMode_FT)
		i90_mdAcquisitionMode_FrameTransfer.addSubMode(i151_mdBinningMode_All)
		i10_sysAcquisition.addMode(i90_mdAcquisitionMode_FrameTransfer)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i93_mdShuffleLinesMode_Normal)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i95_mdShiftNumberMode_Normal)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i123_mdExposureCtrlMode_NoShutter)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i125_mdOutputSourceMode_0x0)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i126_mdOutputSourceMode_0x1)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i127_mdOutputSourceMode_0x2)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i128_mdOutputSourceMode_0x3)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i130_mdOutputSourceMode_TWO)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i129_mdOutputSourceMode_ALL)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i145_mdDimensionsMode_Normal)
		i91_mdAcquisitionMode_Shuffling.addSubMode(i151_mdBinningMode_All)
		i10_sysAcquisition.addMode(i91_mdAcquisitionMode_Shuffling)
		i138_mdAcquisitionMode_NormalWindow.addSubMode(i97_mdSubarrayFeatureMode_On)
		i138_mdAcquisitionMode_NormalWindow.addSubMode(i115_mdExposureCtrlMode_Normal)
		i138_mdAcquisitionMode_NormalWindow.addSubMode(i125_mdOutputSourceMode_0x0)
		i138_mdAcquisitionMode_NormalWindow.addSubMode(i151_mdBinningMode_All)
		i10_sysAcquisition.addMode(i138_mdAcquisitionMode_NormalWindow)
		i152_mdAcquisitionMode_Calibration.addSubMode(i96_mdSubarrayFeatureMode_Off)
		i152_mdAcquisitionMode_Calibration.addSubMode(i124_mdExposureCtrlMode_Calibration)
		i152_mdAcquisitionMode_Calibration.addSubMode(i125_mdOutputSourceMode_0x0)
		i152_mdAcquisitionMode_Calibration.addSubMode(i126_mdOutputSourceMode_0x1)
		i152_mdAcquisitionMode_Calibration.addSubMode(i127_mdOutputSourceMode_0x2)
		i152_mdAcquisitionMode_Calibration.addSubMode(i128_mdOutputSourceMode_0x3)
		i152_mdAcquisitionMode_Calibration.addSubMode(i130_mdOutputSourceMode_TWO)
		i152_mdAcquisitionMode_Calibration.addSubMode(i129_mdOutputSourceMode_ALL)
		i152_mdAcquisitionMode_Calibration.addSubMode(i145_mdDimensionsMode_Normal)
		i152_mdAcquisitionMode_Calibration.addSubMode(i151_mdBinningMode_All)
		i10_sysAcquisition.addMode(i152_mdAcquisitionMode_Calibration)
		i159_mdAcquisitionMode_Engineering.addSubMode(i93_mdShuffleLinesMode_Normal)
		i159_mdAcquisitionMode_Engineering.addSubMode(i95_mdShiftNumberMode_Normal)
		i159_mdAcquisitionMode_Engineering.addSubMode(i96_mdSubarrayFeatureMode_Off)
		i159_mdAcquisitionMode_Engineering.addSubMode(i97_mdSubarrayFeatureMode_On)
		i159_mdAcquisitionMode_Engineering.addSubMode(i160_mdSubarrayFeatureMode_Engineering)
		i159_mdAcquisitionMode_Engineering.addSubMode(i115_mdExposureCtrlMode_Normal)
		i159_mdAcquisitionMode_Engineering.addSubMode(i116_mdExposureCtrlMode_FT)
		i159_mdAcquisitionMode_Engineering.addSubMode(i123_mdExposureCtrlMode_NoShutter)
		i159_mdAcquisitionMode_Engineering.addSubMode(i124_mdExposureCtrlMode_Calibration)
		i159_mdAcquisitionMode_Engineering.addSubMode(i161_mdExposureCtrlMode_Engineering)
		i159_mdAcquisitionMode_Engineering.addSubMode(i125_mdOutputSourceMode_0x0)
		i159_mdAcquisitionMode_Engineering.addSubMode(i126_mdOutputSourceMode_0x1)
		i159_mdAcquisitionMode_Engineering.addSubMode(i127_mdOutputSourceMode_0x2)
		i159_mdAcquisitionMode_Engineering.addSubMode(i128_mdOutputSourceMode_0x3)
		i159_mdAcquisitionMode_Engineering.addSubMode(i129_mdOutputSourceMode_ALL)
		i159_mdAcquisitionMode_Engineering.addSubMode(i130_mdOutputSourceMode_TWO)
		i159_mdAcquisitionMode_Engineering.addSubMode(i162_mdOutputSourceMode_Engineering)
		i159_mdAcquisitionMode_Engineering.addSubMode(i145_mdDimensionsMode_Normal)
		i159_mdAcquisitionMode_Engineering.addSubMode(i146_mdDimensionsMode_FT)
		i159_mdAcquisitionMode_Engineering.addSubMode(i163_mdDimensionsMode_Engineering)
		i159_mdAcquisitionMode_Engineering.addSubMode(i151_mdBinningMode_All)
		i10_sysAcquisition.addMode(i159_mdAcquisitionMode_Engineering)
		i93_mdShuffleLinesMode_Normal.addValue(i92_vlShuffleLines_Full_Range)
		i13_prShuffleLines.addMode(i93_mdShuffleLinesMode_Normal)
		i13_prShuffleLines.addValue(i92_vlShuffleLines_Full_Range)
		i10_sysAcquisition.addParam(i13_prShuffleLines)
		i95_mdShiftNumberMode_Normal.addValue(i94_vlShiftNumber_Full_Range)
		i17_prShiftNumber.addMode(i95_mdShiftNumberMode_Normal)
		i17_prShiftNumber.addValue(i94_vlShiftNumber_Full_Range)
		i10_sysAcquisition.addParam(i17_prShiftNumber)
		i151_mdBinningMode_All.addValue(i147_vlBinning_1x1)
		i151_mdBinningMode_All.addValue(i148_vlBinning_1x2)
		i151_mdBinningMode_All.addValue(i149_vlBinning_2x1)
		i151_mdBinningMode_All.addValue(i150_vlBinning_2x2)
		i78_prBinning.addMode(i151_mdBinningMode_All)
		i78_prBinning.addValue(i147_vlBinning_1x1)
		i78_prBinning.addValue(i148_vlBinning_1x2)
		i78_prBinning.addValue(i149_vlBinning_2x1)
		i78_prBinning.addValue(i150_vlBinning_2x2)
		i10_sysAcquisition.addParam(i78_prBinning)
		i21_sysSubarrayFeature.addMode(i96_mdSubarrayFeatureMode_Off)
		i97_mdSubarrayFeatureMode_On.addSubMode(i98_mdColsMode_Normal)
		i97_mdSubarrayFeatureMode_On.addSubMode(i100_mdoffsetRowMode_Normal)
		i97_mdSubarrayFeatureMode_On.addSubMode(i102_mdRowsMode_Normal)
		i97_mdSubarrayFeatureMode_On.addSubMode(i104_mdoffsetColMode_Normal)
		i21_sysSubarrayFeature.addMode(i97_mdSubarrayFeatureMode_On)
		i160_mdSubarrayFeatureMode_Engineering.addSubMode(i98_mdColsMode_Normal)
		i160_mdSubarrayFeatureMode_Engineering.addSubMode(i100_mdoffsetRowMode_Normal)
		i160_mdSubarrayFeatureMode_Engineering.addSubMode(i102_mdRowsMode_Normal)
		i160_mdSubarrayFeatureMode_Engineering.addSubMode(i104_mdoffsetColMode_Normal)
		i21_sysSubarrayFeature.addMode(i160_mdSubarrayFeatureMode_Engineering)
		i98_mdColsMode_Normal.addValue(i99_vlCols_Full_Range)
		i24_prCols.addMode(i98_mdColsMode_Normal)
		i24_prCols.addValue(i99_vlCols_Full_Range)
		i21_sysSubarrayFeature.addParam(i24_prCols)
		i100_mdoffsetRowMode_Normal.addValue(i101_vloffsetRow_Full_Range)
		i28_proffsetRow.addMode(i100_mdoffsetRowMode_Normal)
		i28_proffsetRow.addValue(i101_vloffsetRow_Full_Range)
		i21_sysSubarrayFeature.addParam(i28_proffsetRow)
		i102_mdRowsMode_Normal.addValue(i103_vlRows_Full_Range)
		i32_prRows.addMode(i102_mdRowsMode_Normal)
		i32_prRows.addValue(i103_vlRows_Full_Range)
		i21_sysSubarrayFeature.addParam(i32_prRows)
		i104_mdoffsetColMode_Normal.addValue(i105_vloffsetCol_Full_Range)
		i36_proffsetCol.addMode(i104_mdoffsetColMode_Normal)
		i36_proffsetCol.addValue(i105_vloffsetCol_Full_Range)
		i21_sysSubarrayFeature.addParam(i36_proffsetCol)
		i10_sysAcquisition.addSubsystem(i21_sysSubarrayFeature)
		i115_mdExposureCtrlMode_Normal.addSubMode(i107_mdOpenShutterMode_Off)
		i115_mdExposureCtrlMode_Normal.addSubMode(i106_mdOpenShutterMode_On)
		i115_mdExposureCtrlMode_Normal.addSubMode(i109_mdExpTimeMode_Normal)
		i115_mdExposureCtrlMode_Normal.addSubMode(i114_mdPixelSpeedMode_FST)
		i115_mdExposureCtrlMode_Normal.addSubMode(i113_mdPixelSpeedMode_MED)
		i115_mdExposureCtrlMode_Normal.addSubMode(i112_mdPixelSpeedMode_SLW)
		i115_mdExposureCtrlMode_Normal.addSubMode(i119_mdnumOfFramesMode_Single)
		i115_mdExposureCtrlMode_Normal.addSubMode(i117_mdnumOfFramesMode_Multiple)
		i40_sysExposureCtrl.addMode(i115_mdExposureCtrlMode_Normal)
		i116_mdExposureCtrlMode_FT.addSubMode(i107_mdOpenShutterMode_Off)
		i116_mdExposureCtrlMode_FT.addSubMode(i110_mdExpTimeMode_FT)
		i116_mdExposureCtrlMode_FT.addSubMode(i114_mdPixelSpeedMode_FST)
		i116_mdExposureCtrlMode_FT.addSubMode(i113_mdPixelSpeedMode_MED)
		i116_mdExposureCtrlMode_FT.addSubMode(i112_mdPixelSpeedMode_SLW)
		i116_mdExposureCtrlMode_FT.addSubMode(i119_mdnumOfFramesMode_Single)
		i116_mdExposureCtrlMode_FT.addSubMode(i117_mdnumOfFramesMode_Multiple)
		i40_sysExposureCtrl.addMode(i116_mdExposureCtrlMode_FT)
		i123_mdExposureCtrlMode_NoShutter.addSubMode(i107_mdOpenShutterMode_Off)
		i123_mdExposureCtrlMode_NoShutter.addSubMode(i109_mdExpTimeMode_Normal)
		i123_mdExposureCtrlMode_NoShutter.addSubMode(i114_mdPixelSpeedMode_FST)
		i123_mdExposureCtrlMode_NoShutter.addSubMode(i113_mdPixelSpeedMode_MED)
		i123_mdExposureCtrlMode_NoShutter.addSubMode(i112_mdPixelSpeedMode_SLW)
		i123_mdExposureCtrlMode_NoShutter.addSubMode(i119_mdnumOfFramesMode_Single)
		i123_mdExposureCtrlMode_NoShutter.addSubMode(i117_mdnumOfFramesMode_Multiple)
		i40_sysExposureCtrl.addMode(i123_mdExposureCtrlMode_NoShutter)
		i124_mdExposureCtrlMode_Calibration.addSubMode(i107_mdOpenShutterMode_Off)
		i124_mdExposureCtrlMode_Calibration.addSubMode(i106_mdOpenShutterMode_On)
		i124_mdExposureCtrlMode_Calibration.addSubMode(i109_mdExpTimeMode_Normal)
		i124_mdExposureCtrlMode_Calibration.addSubMode(i114_mdPixelSpeedMode_FST)
		i124_mdExposureCtrlMode_Calibration.addSubMode(i113_mdPixelSpeedMode_MED)
		i124_mdExposureCtrlMode_Calibration.addSubMode(i112_mdPixelSpeedMode_SLW)
		i124_mdExposureCtrlMode_Calibration.addSubMode(i119_mdnumOfFramesMode_Single)
		i124_mdExposureCtrlMode_Calibration.addSubMode(i117_mdnumOfFramesMode_Multiple)
		i124_mdExposureCtrlMode_Calibration.addSubMode(i122_mdCalibGainMode_Normal)
		i40_sysExposureCtrl.addMode(i124_mdExposureCtrlMode_Calibration)
		i161_mdExposureCtrlMode_Engineering.addSubMode(i106_mdOpenShutterMode_On)
		i161_mdExposureCtrlMode_Engineering.addSubMode(i107_mdOpenShutterMode_Off)
		i161_mdExposureCtrlMode_Engineering.addSubMode(i109_mdExpTimeMode_Normal)
		i161_mdExposureCtrlMode_Engineering.addSubMode(i110_mdExpTimeMode_FT)
		i161_mdExposureCtrlMode_Engineering.addSubMode(i112_mdPixelSpeedMode_SLW)
		i161_mdExposureCtrlMode_Engineering.addSubMode(i113_mdPixelSpeedMode_MED)
		i161_mdExposureCtrlMode_Engineering.addSubMode(i114_mdPixelSpeedMode_FST)
		i161_mdExposureCtrlMode_Engineering.addSubMode(i117_mdnumOfFramesMode_Multiple)
		i161_mdExposureCtrlMode_Engineering.addSubMode(i119_mdnumOfFramesMode_Single)
		i161_mdExposureCtrlMode_Engineering.addSubMode(i122_mdCalibGainMode_Normal)
		i40_sysExposureCtrl.addMode(i161_mdExposureCtrlMode_Engineering)
		i109_mdExpTimeMode_Normal.addValue(i108_vlExpTime_Full_Range)
		i46_prExpTime.addMode(i109_mdExpTimeMode_Normal)
		i110_mdExpTimeMode_FT.addValue(i111_vlExpTime_FT_Range)
		i46_prExpTime.addMode(i110_mdExpTimeMode_FT)
		i46_prExpTime.addValue(i108_vlExpTime_Full_Range)
		i46_prExpTime.addValue(i111_vlExpTime_FT_Range)
		i40_sysExposureCtrl.addParam(i46_prExpTime)
		i117_mdnumOfFramesMode_Multiple.addValue(i118_vlnumOfFrames_Multiple_Range)
		i53_prnumOfFrames.addMode(i117_mdnumOfFramesMode_Multiple)
		i119_mdnumOfFramesMode_Single.addValue(i120_vlnumOfFrames_1)
		i53_prnumOfFrames.addMode(i119_mdnumOfFramesMode_Single)
		i53_prnumOfFrames.addValue(i118_vlnumOfFrames_Multiple_Range)
		i53_prnumOfFrames.addValue(i120_vlnumOfFrames_1)
		i40_sysExposureCtrl.addParam(i53_prnumOfFrames)
		i122_mdCalibGainMode_Normal.addValue(i121_vlCalibGain_Normal_Range)
		i57_prCalibGain.addMode(i122_mdCalibGainMode_Normal)
		i57_prCalibGain.addValue(i121_vlCalibGain_Normal_Range)
		i40_sysExposureCtrl.addParam(i57_prCalibGain)
		i43_sysOpenShutter.addMode(i106_mdOpenShutterMode_On)
		i43_sysOpenShutter.addMode(i107_mdOpenShutterMode_Off)
		i40_sysExposureCtrl.addSubsystem(i43_sysOpenShutter)
		i50_sysPixelSpeed.addMode(i112_mdPixelSpeedMode_SLW)
		i50_sysPixelSpeed.addMode(i113_mdPixelSpeedMode_MED)
		i50_sysPixelSpeed.addMode(i114_mdPixelSpeedMode_FST)
		i40_sysExposureCtrl.addSubsystem(i50_sysPixelSpeed)
		i10_sysAcquisition.addSubsystem(i40_sysExposureCtrl)
		i125_mdOutputSourceMode_0x0.addSubMode(i131_mdRecompositionMode_None)
		i61_sysOutputSource.addMode(i125_mdOutputSourceMode_0x0)
		i126_mdOutputSourceMode_0x1.addSubMode(i131_mdRecompositionMode_None)
		i61_sysOutputSource.addMode(i126_mdOutputSourceMode_0x1)
		i127_mdOutputSourceMode_0x2.addSubMode(i131_mdRecompositionMode_None)
		i61_sysOutputSource.addMode(i127_mdOutputSourceMode_0x2)
		i128_mdOutputSourceMode_0x3.addSubMode(i131_mdRecompositionMode_None)
		i61_sysOutputSource.addMode(i128_mdOutputSourceMode_0x3)
		i129_mdOutputSourceMode_ALL.addSubMode(i134_mdRecompositionMode_QuadCCD)
		i61_sysOutputSource.addMode(i129_mdOutputSourceMode_ALL)
		i130_mdOutputSourceMode_TWO.addSubMode(i133_mdRecompositionMode_Serial)
		i61_sysOutputSource.addMode(i130_mdOutputSourceMode_TWO)
		i162_mdOutputSourceMode_Engineering.addSubMode(i131_mdRecompositionMode_None)
		i162_mdOutputSourceMode_Engineering.addSubMode(i132_mdRecompositionMode_Parallel)
		i162_mdOutputSourceMode_Engineering.addSubMode(i133_mdRecompositionMode_Serial)
		i162_mdOutputSourceMode_Engineering.addSubMode(i134_mdRecompositionMode_QuadCCD)
		i162_mdOutputSourceMode_Engineering.addSubMode(i135_mdRecompositionMode_QuadIR)
		i162_mdOutputSourceMode_Engineering.addSubMode(i136_mdRecompositionMode_CDSQuad)
		i162_mdOutputSourceMode_Engineering.addSubMode(i137_mdRecompositionMode_HawaiiRG)
		i61_sysOutputSource.addMode(i162_mdOutputSourceMode_Engineering)
		i64_sysRecomposition.addMode(i131_mdRecompositionMode_None)
		i64_sysRecomposition.addMode(i132_mdRecompositionMode_Parallel)
		i64_sysRecomposition.addMode(i133_mdRecompositionMode_Serial)
		i64_sysRecomposition.addMode(i134_mdRecompositionMode_QuadCCD)
		i64_sysRecomposition.addMode(i135_mdRecompositionMode_QuadIR)
		i64_sysRecomposition.addMode(i136_mdRecompositionMode_CDSQuad)
		i64_sysRecomposition.addMode(i137_mdRecompositionMode_HawaiiRG)
		i61_sysOutputSource.addSubsystem(i64_sysRecomposition)
		i10_sysAcquisition.addSubsystem(i61_sysOutputSource)
		i145_mdDimensionsMode_Normal.addSubMode(i140_mduiRowsMode_Normal)
		i145_mdDimensionsMode_Normal.addSubMode(i144_mduiColsMode_Normal)
		i67_sysDimensions.addMode(i145_mdDimensionsMode_Normal)
		i146_mdDimensionsMode_FT.addSubMode(i142_mduiRowsMode_Half)
		i146_mdDimensionsMode_FT.addSubMode(i144_mduiColsMode_Normal)
		i67_sysDimensions.addMode(i146_mdDimensionsMode_FT)
		i163_mdDimensionsMode_Engineering.addSubMode(i140_mduiRowsMode_Normal)
		i163_mdDimensionsMode_Engineering.addSubMode(i142_mduiRowsMode_Half)
		i163_mdDimensionsMode_Engineering.addSubMode(i144_mduiColsMode_Normal)
		i67_sysDimensions.addMode(i163_mdDimensionsMode_Engineering)
		i140_mduiRowsMode_Normal.addValue(i139_vluiRows_Full_Range)
		i70_pruiRows.addMode(i140_mduiRowsMode_Normal)
		i142_mduiRowsMode_Half.addValue(i141_vluiRows_FTRange)
		i70_pruiRows.addMode(i142_mduiRowsMode_Half)
		i70_pruiRows.addValue(i139_vluiRows_Full_Range)
		i70_pruiRows.addValue(i141_vluiRows_FTRange)
		i67_sysDimensions.addParam(i70_pruiRows)
		i144_mduiColsMode_Normal.addValue(i143_vluiCols_Full_Range)
		i74_pruiCols.addMode(i144_mduiColsMode_Normal)
		i74_pruiCols.addValue(i143_vluiCols_Full_Range)
		i67_sysDimensions.addParam(i74_pruiCols)
		i10_sysAcquisition.addSubsystem(i67_sysDimensions)
		i7_sysVariants.addSubsystem(i10_sysAcquisition)
		i4_sysFirmware.addSubsystem(i7_sysVariants)
		i1_sysARCGenIII.addSubsystem(i4_sysFirmware)
	end
end

thismodel = ARCGenIIIPORIS.new(16)
root = thismodel.getRoot

puts(root.getName)
puts(root.getSelectedMode.getName)

bin = root.getDescendantParamFromName("Binning")
puts(bin.getName)
puts(bin.getSelectedMode.getName)
puts(bin.getSelectedValue.getName)

md = root.getModeFromName('ARCGenIIIMode_Real')
root.selectMode(md)
puts(root.getName)
puts(root.getSelectedMode.getName)
puts(bin.getName)
puts(bin.getSelectedMode.getName)
puts(bin.getSelectedValue.getName)

root.selectMode(root.unknownMode)
puts(root.getName)
puts(root.getSelectedMode.getName)
puts(bin.getName)
puts(bin.getSelectedMode.getName)
puts(bin.getSelectedValue.getName)
